name: LocalRetro_disctributed
environment:
  image: determinedai/environments:cuda-10.2-pytorch-1.7-tf-1.15-gpu-mpi-0.21.0
hyperparameters:
    global_batch_size: 128
    learning_rate: 1.0e-4
    weight_decay: 1.0e-6
    schedule_step: 10
    node_out_feats: 320
    drop_out: 0.2
    attention_layers: 2
    attention_heads: 8
    num_step_message_passing: 6
    edge_hidden_feats: 64
    patience: 5
    max_clip: 20
    dataset: 'USPTO_50K'
    mode: 'train'
searcher:
    name: single
    metric: val_loss 
    max_length:
        epochs: 50           
    smaller_is_better: true
records_per_epoch: 40000
min_checkpoint_period:
   epochs: 1
min_validation_period:
    epochs: 1                   
entrypoint: python3 -m determined.launch.torch_distributed --rdzv_endpoint=$CUSTOM_RDZV_ADDR -- --trial model_def:LocalRetroPytorch
max_restarts: 0
workspace: poc
project: localretro
resources:
    resource_pool: compute-pool
    slots_per_trial: 8
profiling:
  enabled: true
  begin_on_batch: 0
  end_after_batch: null

