name: localretro-coreapi-stage-4-distributed
entrypoint: >-
  python3 -m determined.launch.torch_distributed
  python3 scripts/Train.py -d USPTO_50K
environment:
  image: determinedai/environments:cuda-10.2-pytorch-1.7-tf-1.15-gpu-mpi-0.21.0
hyperparameters:
    global_batch_size: 256
    learning_rate: 1.0e-4
    weight_decay: 1.0e-6
    schedule_step: 10
    node_out_feats: 320
    drop_out: 0.2
    attention_layers: 2
    attention_heads: 8
    num_step_message_passing: 6
    edge_hidden_feats: 64
    patience: 5
    max_clip: 20
    dataset: 'USPTO_50K'
    mode: 'train'
max_restarts: 0
records_per_epoch: 40016
searcher:
  name: single
  metric: val_loss
  max_length:
    epochs: 3
# To be removed or replaced by custom cluster information
workspace: poc
project: localretro_dev
resources:
    resource_pool: compute-pool 
    slots_per_trial: 16
